name: shesha-4.x.x

# This workflow is designed to build the shesha-core and shesha-reactjs applications 
# and then publish them to their respective repositories i.e. nuget and npmjs

on:
  push:
    branches: 
      - main
    paths:
      - shesha-reactjs/**
      - shesha-core/**
  pull_request:
    types:
      - closed
    branches: 
      - main
    paths:
      - shesha-reactjs/**
      - shesha-core/**
env:
  NODE_VERSION: '15'
  PYTHON_VERSION: '2.7.18'
  DOTNET_VERSION: '6.x'

jobs:
  # build the project
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          clean: true
          ref: main

      # ============ SETUP ENVIRONMENTS ===============

      # Setup Node for shesha-reactjs
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          registry-url: 'https://registry.npmjs.org'
      # Setup Python for for shesha-reactjs (solution currently needs python2 to run)
      - name: Setup Python ${{ env.PYTHON_VERSION }}
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      # Setup DOTNET for shesha-core
      - name: Setup .NET Core SDK ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # ============ RESOLVE DEPENDENCIES ===============

      # Install dependencies for shesha-reactjs
      - name: Install Dependencies
        run: npm install --legacy-peer-deps
        working-directory: ./shesha-reactjs
      

      # prepare shesha-reactjs for pipeline
      - name: Prepare shesha-reactjs for Pipeline
        run: npm run prepare
        working-directory: ./shesha-reactjs
      # tag shesha-reactjs
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ''
      # update package.json tag
      - name: Update package.json
        uses: reedyuk/npm-version@1.1.1
        with:
          version: ${{ steps.tag_version.outputs.new_tag }}
          package: 'shesha-reactjs/'
          # git-tag-version: 'true'
      # build shesha-reactjs for production
      - name: Build shesha-reactjs for Production
        run: npm run build
        working-directory: ./shesha-reactjs
      # create github release
      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: shesha-reactjs@${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
      # publish shesha-reactjs to npmjs registry
      - name: Publish shesha-reactjs to npmjs registry
        run: npm publish --access public
        working-directory: ./shesha-reactjs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_API_KEY }}
