name: tag-release-branch-updates

on:
  push:
    branches:
      - 'releases/**'
env:
  NODE_VERSION: '15'
  PYTHON_VERSOIN: '2.7.18'
  DOTNET_VERSION: '6.x'

jobs:
  # build the project
  build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:

      # ============ CHECKOUT BRANCH ===============

      # checkout latest code
      - name: Get Sources
        uses: actions/checkout@v2
        with:
          clean: true


      # ============ TAG BRANCH ===============
      
      - run: git tag ${GITHUB_BASE_REF}